# https://peps.python.org/pep-0517/
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

# https://hatch.pypa.io/latest/config/metadata/
[tool.hatch.version]
source = "vcs"

# read more about configuring hatch at:
# https://hatch.pypa.io/latest/config/build/
[tool.hatch.build.targets.wheel]
packages = ["src/fractal_helper_tasks"]


# Project metadata (see https://peps.python.org/pep-0621)
[project]
name = "fractal-helper-tasks"
dynamic = ["version"]
description = "Collection of Fractal helper tasks"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [
    { name = "Joel Luethi", email = "joel.luethi@uzh.ch" },
]

# Required Python version and dependencies
requires-python = ">=3.11"
dependencies = [
    "ngio>=0.2.2,<0.3.0",
    "fractal-task-tools==0.0.12",
]

# Optional dependencies (e.g. for `pip install -e ".[dev]"`, see
# https://peps.python.org/pep-0621/#dependencies-optional-dependencies)
[project.optional-dependencies]
dev = ["devtools", "hatch", "pytest", "requests", "jsonschema", "ruff", "pre-commit", "pooch"]
test = ["pytest", "pytest-cov"]

# https://docs.astral.sh/ruff
[tool.ruff]
line-length = 88
target-version = "py39"
src = ["src"]

# https://docs.astral.sh/ruff/rules
[tool.ruff.lint]
pydocstyle = { convention = "google" }
select = [
    "E",    # style errors
    "W",    # style warnings
    "F",    # flakes
    "D",    # pydocstyle
    "D417", # Missing argument descriptions in Docstrings
    "I",    # isort
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
    "B",    # flake8-bugbear
    "A001", # flake8-builtins
    "RUF",  # ruff-specific rules
    "TCH",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
]
extend-select = [
    "D417", # Missing argument descriptions in Docstrings
]
ignore = [
    "D401", # First line should be in imperative mood (remove to opt in)
    "C408", # Unnecessary `dict` call
    "D415", # First line should end with a period (remove to opt in)
    "UP022" # Used in validate_command test, waiting for template fix
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "S"]

# https://docs.astral.sh/ruff/formatter/
[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 89
skip-magic-trailing-comma = false  # default is false

[tool.coverage.run]
# Include only the specific package directories for coverage, exclude tests
include = [
    "src/fractal_helper_tasks/*"
]
omit = [
    "*/tests/*",
    "*_test.py",
    "setup.py"
]
