name: CI (build and test)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - os: macos-latest
            python-version: '3.9'
          - os: macos-latest
            python-version: '3.10'
    name: "Core, Python ${{ matrix.python-version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: python -m pip install -e .[dev]

      - name: Install some testing dependencies (hard-coded)
        run: python -m pip install pytest pytest-cov devtools jsonschema requests wget pooch

      - name: Regenerate the manifest
        run: python src/fractal_helper_tasks/dev/create_manifest.py

      - name: Cache Pooch folder
        id: cache-pooch-folder
        uses: actions/cache@v3
        with:
          path: ~/.cache/pooch
          key: pooch-cache

      - name: Check if manifest has changed
        run: |
          if [ -n "$(git diff --exit-code ./src/fractal_helper_tasks/__FRACTAL_MANIFEST__.json)" ]; then
          echo "__FRACTAL_MANIFEST__.json has changed. Please run 'python src/fractal_helper_tasks/dev/create_manifest.py' and commit the changes."
            exit 1
          else
            echo "__FRACTAL_MANIFEST__.json has not changed."
          fi

      - name: Test tasks with pytest
        run: pytest --color=yes --cov --cov-report=xml --cov-report=term-missing -s --log-cli-level debug
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jluethi/fractal-helper-tasks
  
  deploy:
    name: Deploy
    needs: tests
    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing on PyPi
      # see https://docs.pypi.org/trusted-publishers/
      id-token: write
      # This permission allows writing releases
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 👷 Build
        run: |
          python -m pip install build
          python -m build

      - name: 🚢 Publish to PyPI
        # TODO remove the "if: false" line when the package is ready for pypi release
        if: false
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: './dist/*'