name: CI (pip)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    name: "Core, Python ${{ matrix.python-version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: python -m pip install .[dev,test]

      - name: Install some testing dependencies (hard-coded)
        run: python -m pip install pytest devtools jsonschema requests wget pooch

      - name: Cache Pooch folder
        id: cache-pooch-folder
        uses: actions/cache@v3
        with:
          path: ~/.cache/pooch
          key: pooch-cache

      - name: Test tasks with pytest
        run: pytest --color=yes --cov --cov-report=xml --cov-report=term-missing -s --log-cli-level debug

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1